# Importar librerías

In [ ]:
import numpy as np
import pandas as pd

# Leer datos

In [67]:
df = pd.read_csv('Resultados.csv')

date = df.values[:,0]
j1 = df.values[:,1]
j2 = df.values[:,2]
j3 = df.values[:,3]
j4 = df.values[:,4]

set1 = df.values[:,5:7]
set2 = df.values[:,7:9]
set3 = df.values[:,9:11]

# Procesar información

In [68]:
players = ['Ale', 'Alan', 'Lucho', 'Rodrigo', 'Pato', 'Diego', 'Seba T.', 'Matias', 'Seba G.']

score_default = []
for player in players:
    score_default = np.append(score_default,5000)

# Cálculo de puntaje base

In [69]:
pt_p1 = np.zeros(set1.shape[0])
pt_p2 = np.zeros(set1.shape[0])

for i in range(set1.shape[0]):
    
    sets_p1 = 0
    sets_p2 = 0
    
    #Determinar ganador, si hubo
    if set1[i,0] != set1[i,1]:
        if set1[i,0] >= 6 or set1[i,1] >= 6:
            if set1[i,0] > set1[i,1]:
                sets_p1 = sets_p1 + 1
                sets_p2 = sets_p2 + 0
            elif set1[i,0] < set1[i,1]:
                sets_p1 = 0
                sets_p2 = 1
                
    if set2[i,0] != set2[i,1]:        
        if set2[i,0] >= 6 or set2[i,1] >= 6:
            if set2[i,0] > set2[i,1]:
                sets_p1 = sets_p1 + 1
                sets_p2 = sets_p2 + 0
            elif set2[i,0] < set2[i,1]:
                sets_p1 = sets_p1 + 0
                sets_p2 = sets_p2 + 1
                
    if set3[i,0] != set3[i,1]:         
        if set3[i,0] >= 6 or set3[i,1] >= 6:
            if set3[i,0] > set3[i,1]:
                sets_p1 = sets_p1 + 1
                sets_p2 = sets_p2 + 0
            elif set3[i,0] < set3[i,1]:
                sets_p1 = sets_p1 + 0
                sets_p2 = sets_p2 + 1

    #Asigmar puntos por partido ganado
    if sets_p1 > sets_p2:
        w_p1 = 50
        w_p2 = 0
    elif sets_p1 < sets_p2:
        w_p1 = 0
        w_p2 = 50
    else:
        w_p1 = 0
        w_p2 = 0

    #Calcular puntaje base (partido, sets, games)
    pt_p1[i] = w_p1 + sets_p1*20 + (set1[i,0] + set2[i,0] + set3[i,0])*5
    pt_p2[i] = w_p2 + sets_p2*20 + (set1[i,1] + set2[i,1] + set3[i,1])*5
        

# Calcular ranking y aplicar handicap

In [77]:
score = score_default.copy()
score = np.array(score)
ranking = np.zeros((pt_p1.shape[0],score.shape[0]))

for i in range(pt_p1.shape[0]):
    #Índices de jugadores
    idx_j1 = [j for j in range(len(players)) if players[j] == j1[i]]
    idx_j2 = [j for j in range(len(players)) if players[j] == j2[i]]
    idx_j3 = [j for j in range(len(players)) if players[j] == j3[i]]
    idx_j4 = [j for j in range(len(players)) if players[j] == j4[i]]
    
    #Handicap
    hcp_p1 = (score[idx_j3] + score[idx_j4]) / (score[idx_j1] + score[idx_j2])
    hcp_p2 = (score[idx_j1] + score[idx_j2]) / (score[idx_j3] + score[idx_j4])
    
    #Cálculo puntos por partido
    score[idx_j1] = score[idx_j1] + pt_p1[i]*hcp_p1 - pt_p2[i]*hcp_p2
    score[idx_j2] = score[idx_j2] + pt_p1[i]*hcp_p1 - pt_p2[i]*hcp_p2
    score[idx_j3] = score[idx_j3] - pt_p1[i]*hcp_p1 + pt_p2[i]*hcp_p2
    score[idx_j4] = score[idx_j4] - pt_p1[i]*hcp_p1 + pt_p2[i]*hcp_p2
    
    #Escribir ranking
    ranking[i,:] = np.rint(score)

In [78]:
print(ranking)

[[4995. 5005. 4995. 5005. 5000. 5000. 5000. 5000. 5000.]
 [5005. 4995. 4995. 4995. 5000. 5000. 5010. 5000. 5000.]
 [5125. 4875. 4875. 4995. 5000. 5000. 5130. 5000. 5000.]
 [5242. 4758. 4993. 4877. 5000. 5000. 5130. 5000. 5000.]
 [5312. 4688. 5063. 4808. 5000. 5000. 5130. 5000. 5000.]
 [5312. 4555. 5195. 4675. 5000. 5000. 5262. 5000. 5000.]
 [5151. 4716. 5357. 4514. 5000. 5000. 5262. 5000. 5000.]
 [5293. 4575. 5215. 4514. 5000. 5000. 5404. 5000. 5000.]
 [5422. 4704. 5086. 4514. 5000. 5000. 5275. 5000. 5000.]
 [5258. 4867. 5250. 4350. 5000. 5000. 5275. 5000. 5000.]
 [5122. 5003. 5114. 4486. 5000. 5000. 5275. 5000. 5000.]
 [5017. 5108. 5009. 4590. 5000. 5000. 5275. 5000. 5000.]
 [5164. 4961. 5156. 4444. 5000. 5000. 5275. 5000. 5000.]
 [5011. 5114. 5309. 4290. 5000. 5000. 5275. 5000. 5000.]
 [4913. 5212. 5211. 4290. 5000. 5000. 5374. 5000. 5000.]
 [5011. 5114. 5211. 4290. 5000. 4902. 5472. 5000. 5000.]
 [4903. 5223. 5102. 4290. 5000. 4902. 5580. 5000. 5000.]
 [5051. 5074. 5251. 4290. 5000.